name: Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configura o Python
      - name: Configura o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Instala as dependências
      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executa os testes
      - name: Executa os testes
        run: |
          pytest --maxfail=1 --disable-warnings -q
